### ISSUE TITLE
Occasional OSError: Failed SSL handshake

### ISSUE THREAD

**Issue by calcut** [calcut/circuitpy_mcu#1]
```
Publishing to AIO:
ERROR Traceback (most recent call last):
  File "circuitpy_mcu/mcu.py", line 358, in aio_send
  File "adafruit_io/adafruit_io.py", line 438, in publish
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 634, in publish
OSError: Failed SSL handshake

ERROR Error publishing data to AIO
Code stopped by unhandled exception:
Traceback (most recent call last):
  File "/circuitpy_septic_tank/methane_gascard.py", line 269, in <module>
  File "/circuitpy_septic_tank/methane_gascard.py", line 265, in main
  File "/circuitpy_septic_tank/methane_gascard.py", line 226, in publish_feeds
  File "circuitpy_mcu/mcu.py", line 358, in aio_send
  File "adafruit_io/adafruit_io.py", line 438, in publish
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 634, in publish
OSError: Failed SSL handshake

Performing a hard reset in 15s
```

**Comment by calcut** [comment]
Unsure what causes this, should add better logging.
Current work around is a hard reset which isn't ideal!
